openapi: 3.0.2
info:
  title: "Wikipedia Search function"
  description: "A simple API that searches stock code from stock name"
  version: "1.0.0"
servers: 
  - url: "https://us-central1-pivotal-equinox-423908-k7.cloudfunctions.net"

paths:
  /stock_fundamental_values: # name of the Cloud Function
    post:
      summary: "To basic metrics of a company in stock market"
      operationId: "fundamental_stock_metrics"
      requestBody:
        description: Query
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nse_bse_reports'
      responses:
        "200":
          description: "A successful response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Book Value:
                    type: integer
                  Current Price:
                    type: integer
                  Dividend Yield:
                    type: number
                  Face Value:
                    type: integer
                  High / Low:
                    type: object
                  Market Cap:
                    type: integer
                  ROCE:
                    type: number
                  ROE:
                    type: number
                  Stock P/E:
                    type: number

components:
  schemas:
    nse_bse_reports:
      required:
        - company name
      type: object
      properties:
        company name:
          type: string