openapi: 3.0.2
info:
  title: "Wikipedia Search function"
  description: "A simple API that searches stock code from stock name"
  version: "1.0.0"
servers: 
  - url: "https://us-central1-pivotal-equinox-423908-k7.cloudfunctions.net"

paths:
  /news: # name of the Cloud Function
    post:
      summary: "Serches news of a stock"
      operationId: "stock_news"
      requestBody:
        description: Query
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/news'
      responses:
        "200":
          description: "A successful response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  news:
                    type: string
                  
components:
  schemas:
    news:
      required:
        - company name
      type: object
      properties:
        company name:
          type: string